Repository tobac-project/tobac, pull requests merged in 2022-11, with the labels that each got.

#199 Sort feature detection thresholds based on target
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
Labels: bug

#136 Merge Split algorithm added
  doc/index.rst
  doc/merge_split.rst
  doc/merge_split_out_vars.csv
  doc/tobac.rst
  tobac/__init__.py
  tobac/merge_split.py
  tobac/tests/test_merge_split.py
  tobac/utils.py
Labels: enhancement

#179 Porting the converting decorators from v2
  tobac/tests/test_convert.py
  tobac/utils.py
Labels: enhancement, v2.x compatibility

#207 Deprecate some analysis functions
  tobac/analysis.py
Labels: Refactor

#191 Split up utils module similar to `v2.0-dev`
  doc/tobac.rst
  setup.py
  tobac/feature_detection.py
  tobac/tests/test_convert.py
  tobac/tests/test_utils.py
  tobac/utils.py
  tobac/utils/__init__.py
  tobac/utils/general.py
  tobac/utils/internal.py
  tobac/utils/mask.py
Labels: v2.x compatibility, In Review, Refactor

#204 Update requirements to require scikit-learn and purge old requirements
  .github/workflows/codecov-CI.yml
  README.md
  requirements.txt
  setup.py
Labels: enhancement
