Repository tobac-project/tobac, pull requests merged in 2022-09, with the labels that each got.

#172 Merging `hotfix` into `main` for v1.3.3
  CHANGELOG.md
  setup.py
  tobac/tests/test_tracking.py
  tobac/tracking.py
Labels: release

#173 Docstrings + Bugfixes for utils.py
  tobac/utils.py
Labels: enhancement, documentation

#168 Resetting parameters and adding exceptions for adaptive search
  tobac/tests/test_tracking.py
  tobac/tracking.py
Labels: enhancement

#177 Raise NotImplementedError when using extrapolation
  tobac/tests/test_tracking.py
  tobac/tracking.py
Labels: bug
