Repository tobac-project/tobac, pull requests merged in 2022-07, with the labels that each got.

#147 Added depreciation warnings to two segmentation functions
  tobac/segmentation.py
Labels: enhancement

#151 Fixing `weighted_abs` feature position
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
Labels: bug

#154 Revert "Added depreciation warnings to two segmentation functions"
  tobac/segmentation.py
Labels: bug

#156 Update version number and changelog in prep for 1.3.2
  CHANGELOG.md
  setup.py
Labels: release

#155 Docstrings for plotting.py
  tobac/plotting.py
Labels: enhancement, documentation

#161 Use a specified version of black in workflow
  .github/workflows/check_formatting.yml
  CONTRIBUTING.md
Labels: enhancement

#157 Merge `dev` into `main` for v1.3.2
  .coveragerc
  .github/workflows/codecov-CI.yml
  CHANGELOG.md
  setup.py
  tobac/feature_detection.py
  tobac/tests/Dockerfile-coverage
  tobac/tests/test_feature_detection.py
  tobac/tracking.py
Labels: release
