Repository tobac-project/tobac, pull requests merged in 2022-10, with the labels that each got.

#186 New function to combine feature dataframes
  doc/big_datasets.rst
  doc/index.rst
  tobac/tests/test_utils.py
  tobac/utils.py
Labels: enhancement, documentation

#187 Bug fix: Assure that feature dataframe indices are unique
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
Labels: bug, enhancement

#193 Deprecate Python 3.6 and lower support
  .gitignore
  README.md
  setup.py
  tobac/__init__.py
Labels: enhancement

#195 Documentation update addressing why not all features have segmented areas
  doc/features_without_segmented_area.rst
  doc/images/feature_outside_of_threshold_area.png
  doc/images/feature_outside_of_threshold_area_extreme.png
  doc/images/features_without_segment.png
  doc/index.rst
  doc/segmentation_out_vars.csv
  doc/segmentation_output.rst
  doc/segmentation_parameters.rst
Labels: documentation

#197 Updates to `README.md`
  README.md
Labels: documentation
