Repository tobac-project/tobac, pull requests merged in 2022-06, with the labels that each got.

#130 Fix `map_tracks` with untracked cell number change
  tobac/plotting.py
Labels: bug

#120 added pull_request_template.md in .github/
  .github/pull_request_template.md
Labels: enhancement

#142 Version bump and changelog addition
  CHANGELOG.md
  setup.py
Labels: release

#144 Merge `dev` into `main` for 1.3.1 release
  .github/pull_request_template.md
  CHANGELOG.md
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  setup.py
  tobac/plotting.py
Labels: release

#124 Add code coverage via Github Actions
  .coveragerc
  .github/workflows/codecov-CI.yml
  tobac/tests/Dockerfile-coverage
Labels: enhancement

#140 Correct parameter for the subnet size in adaptive search
  tobac/tracking.py
Labels: bug
