Repository tobac-project/tobac, pull requests merged in 2022-04, with the labels that each got.

#103 bug fix: added missing 'raise' in get_spacing to actually raise ValueError
  tobac/utils/general.py
Labels: bug

#105 added missing 'raise' in get_spacings to actually raise ValueError
  tobac/utils.py
Labels: bug

#110 Fix depreciation warnings that we can fix
  tobac/feature_detection.py
  tobac/tests/test_testing.py
  tobac/tests/test_tracking.py
Labels: bug

#100 Remove setting backend to `agg` automatically
  tobac/plotting.py
Labels: bug, enhancement

#112 Add changelog file
  CHANGELOG.md
Labels: documentation

#114 Add URLs to changelog
  CHANGELOG.md
Labels: documentation

#111 Version 1.3 release candidate
  .github/workflows/check_formatting.yml
  .github/workflows/docker-image.yml
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  conda-requirements.txt
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  setup.py
  tobac/__init__.py
  tobac/analysis.py
  tobac/centerofgravity.py
  tobac/feature_detection.py
  tobac/plotting.py
  tobac/segmentation.py
  tobac/testing.py
  tobac/tests/test_feature_detection.py
  tobac/tests/test_import.py
  tobac/tests/test_sample_data.py
  tobac/tests/test_segmentation.py
  tobac/tests/test_testing.py
  tobac/tests/test_tracking.py
  tobac/tracking.py
  tobac/utils.py
  tobac/wrapper.py
Labels: release

#113 Update example notebooks to check if data is present
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
Labels: enhancement

#116 updated get_spacings() to calculate dxy from 1D or 2D lat-lon values, independent of their dimension order
  tobac/utils/general.py
Labels: bug
