Repository tobac-project/tobac, pull requests merged in 2023-07, with the labels that each got.

#283 Feature: Only detect features if all previous thresholds have been met
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
Labels: enhancement

#305 Solving the bug in API docs rendering
  doc/conf.py
  doc/requirements.txt
Labels: bug, documentation

#242 Adding ability to track on one dataset, segment on another
  .github/workflows/check_notebooks.yml
  doc/images/sat_radar_combined.png
  doc/index.rst
  doc/transform_segmentation.rst
  example_requirements.txt
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/tests/test_feature_detection.py
  tobac/tests/test_segmentation.py
  tobac/tests/test_utils.py
  tobac/tests/test_utils_internal.py
  tobac/tracking.py
  tobac/utils/__init__.py
  tobac/utils/general.py
  tobac/utils/internal.py
Labels: enhancement

#300 Allow preserving of original feature numbers (if not unique) in `combine_tobac_feats`
  doc/conf.py
  tobac/tests/test_utils.py
  tobac/utils/__init__.py
  tobac/utils/general.py
Labels: enhancement

#309 v1.5.0 Changelog
  CHANGELOG.md
Labels: release

#308 V1.5.0 notebooks
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  run_notebooks.sh
Labels: release
