Repository tobac-project/tobac, pull requests merged in 2023-11, with the labels that each got.

#341 Reorganization of internal utilities and adding type hints for internal utils
  setup.py
  tobac/utils/internal/__init__.py
  tobac/utils/internal/basic.py
  tobac/utils/internal/iris_utils.py
  tobac/utils/internal/xarray_utils.py
Labels: Refactor, xarray transition

#337 Add type hints to feature detection
  requirements.txt
  tobac/feature_detection.py
Labels: good first issue, Refactor, xarray transition

#353 Add matrix CI Tests on multiple Python versions and OS versions
  .github/workflows/matrix_ci.yml
  dev_requirements.txt
  environment-ci.yml
  example_requirements.txt
  tobac/testing.py
  tobac/utils/general.py
Labels: enhancement, workflow

#365 Update references and documentation on threshold use
  doc/index.rst
  doc/publications.rst
  doc/segmentation_parameters.rst
  doc/threshold_detection_parameters.rst
  tobac/feature_detection.py
  tobac/segmentation.py
Labels: documentation

#359 Wrap decorators to preserve docstrings and move to separate module
  tobac/tests/test_convert.py
  tobac/utils/bulk_statistics.py
  tobac/utils/decorators.py
  tobac/utils/internal/basic.py
  tobac/utils/periodic_boundaries.py
Labels: enhancement, documentation

#368 Update bulk statistics to use multiple fields correctly
  doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/tests/test_segmentation.py
  tobac/tests/test_utils.py
  tobac/tests/test_utils_bulk_statistics.py
  tobac/utils/bulk_statistics.py
Labels: bug
