Repository tobac-project/tobac, pull requests merged in 2023-09, with the labels that each got.

#336 Fix to readthedocs builds
  .readthedocs.yml
  CHANGELOG.md
Labels: bug, documentation

#340 Fix for Jupyter Notebook CI
  .github/workflows/check_notebooks.yml
  CHANGELOG.md
  example_requirements.txt
Labels: bug

#335 Graceful handling of Numba import errors
  CHANGELOG.md
  tobac/utils/internal.py
Labels: bug

#323 Merge `RC_v1.5_hotfix` into `main`
  .github/workflows/check_notebooks.yml
  .readthedocs.yml
  CHANGELOG.md
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  example_requirements.txt
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  tobac/__init__.py
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
  tobac/utils/__init__.py
  tobac/utils/general.py
  tobac/utils/internal.py
Labels: release

#343 fixed duplicate index issue in test_trackpy_predict
  tobac/tests/test_tracking.py
Labels: bug, release, High Priority
