Repository tobac-project/tobac, pull requests merged in 2023-02, with the labels that each got.

#235 Update documentation for v1.4.1
  .zenodo.json
  CHANGELOG.md
  tobac/__init__.py
Labels: release

#209 Add 3D support to feature detection and tracking
  .gitignore
  doc/analysis.rst
  doc/big_datasets.rst
  doc/conf.py
  doc/data_input.rst
  doc/feature_detection_3D_out_vars.csv
  doc/feature_detection_output.rst
  doc/feature_detection_overview.rst
  doc/features_without_segmented_area.rst
  doc/index.rst
  doc/modules.rst
  doc/publications.rst
  doc/segmentation_parameters.rst
  doc/threshold_detection_parameters.rst
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/testing.py
  tobac/tests/Dockerfile
  tobac/tests/test_convert.py
  tobac/tests/test_feature_detection.py
  tobac/tests/test_merge_split.py
  tobac/tests/test_segmentation.py
  tobac/tests/test_testing.py
  tobac/tests/test_tracking.py
  tobac/tests/test_utils.py
  tobac/tests/test_utils_internal.py
  tobac/tracking.py
  tobac/utils/__init__.py
  tobac/utils/general.py
  tobac/utils/internal.py
Labels: enhancement

#127 Adding periodic boundary condition support to tobac
  .gitignore
  doc/feature_detection_output.rst
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/testing.py
  tobac/tests/Dockerfile
  tobac/tests/test_convert.py
  tobac/tests/test_feature_detection.py
  tobac/tests/test_merge_split.py
  tobac/tests/test_pbc_utils.py
  tobac/tests/test_segmentation.py
  tobac/tests/test_testing.py
  tobac/tests/test_tracking.py
  tobac/tests/test_utils.py
  tobac/tracking.py
  tobac/utils/__init__.py
  tobac/utils/general.py
  tobac/utils/internal.py
  tobac/utils/periodic_boundaries.py
Labels: enhancement

#244 Add target option to `filter_min_distance`
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
Labels: bug, enhancement

#247 Hotfix v1.4.2 to resolve bug with ncells in feature dataframe #246
  CHANGELOG.md
  tobac/__init__.py
  tobac/segmentation.py
  tobac/tests/test_feature_detection.py
  tobac/tests/test_segmentation.py
Labels: bug

#251 Move fixes to `filter_min_distance` and 2d coordinate interpolation to v1.4.
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
  tobac/utils.py
Labels: bug

#256 Merge `hotfix` into `main` for v1.4.2
  CHANGELOG.md
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  tobac/__init__.py
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/tests/test_feature_detection.py
  tobac/tests/test_segmentation.py
  tobac/utils.py
Labels: release

#250 Fix 2d coordinate interpolation
  tobac/utils/general.py
Labels: bug
