Repository tobac-project/tobac, pull requests merged in 2023-12, with the labels that each got.

#361 Add tests for `time_cell_min` and update documentation for the parameter
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/tests/test_tracking.py
  tobac/tracking.py
Labels: documentation

#373 Add Pylint to Workflow
  .github/workflows/pylint.yml
Labels: enhancement

#376 Uncomment `dist_func` parameter to enable PBCs with predictive tracking
  tobac/tests/test_tracking.py
  tobac/tracking.py
Labels: bug, Small Change

#384 Fix issue with numba and PBC dist func
  tobac/tests/test_tracking.py
  tobac/tracking.py
Labels: bug

#381 Update version number, changelog and notebooks for 1.5.2 release
  CHANGELOG.md
  doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  tobac/__init__.py
Labels: release

#387 Merge RC v1.5.2 into main
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/check_formatting.yml
  .github/workflows/codecov-CI.yml
  .github/workflows/matrix_ci.yml
  .github/workflows/pylint.yml
  .readthedocs.yml
  CHANGELOG.md
  dev_requirements.txt
  doc/bulk_statistics/index.rst
  doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  doc/feature_detection_output.rst
  doc/index.rst
  doc/publications.rst
  doc/requirements.txt
  doc/segmentation_out_vars_statistics.csv
  doc/segmentation_output.rst
  doc/segmentation_parameters.rst
  doc/threshold_detection_parameters.rst
  environment-ci.yml
  example_requirements.txt
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  requirements.txt
  setup.py
  tobac/__init__.py
  tobac/analysis.py
  tobac/feature_detection.py
  tobac/plotting.py
  tobac/segmentation.py
  tobac/testing.py
  tobac/tests/test_convert.py
  tobac/tests/test_segmentation.py
  tobac/tests/test_tracking.py
  tobac/tests/test_utils.py
  tobac/tests/test_utils_bulk_statistics.py
  tobac/tracking.py
  tobac/utils/__init__.py
  tobac/utils/bulk_statistics.py
  tobac/utils/decorators.py
  tobac/utils/general.py
  tobac/utils/internal.py
  tobac/utils/internal/__init__.py
  tobac/utils/internal/basic.py
  tobac/utils/internal/iris_utils.py
  tobac/utils/internal/xarray_utils.py
  tobac/utils/periodic_boundaries.py
Labels: release
