Repository tobac-project/tobac, pull requests merged in 2024-03, with the labels that each got.

#380 Add ability to save whether or not an `iris` to `xarray` conversion happened in the decorators
  .github/workflows/check_formatting.yml
  tobac/tests/test_convert.py
  tobac/utils/bulk_statistics.py
  tobac/utils/decorators.py
  tobac/utils/general.py
  tobac/utils/internal/basic.py
Labels: enhancement, xarray transition

#416 Fix decorator issues with 1.5.x branch
  tobac/analysis.py
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/utils/general.py
Labels: bug

#422 Release 1.5.3
  CHANGELOG.md
  doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  examples/Basics/Idealized-Case-1_Tracking-of-a-Test-Blob-in-2D.ipynb
  examples/Basics/Idealized-Case-2_Two_crossing_Blobs.ipynb
  examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_1.ipynb
  examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_2.ipynb
  examples/Basics/Methods-and-Parameters-for-Linking.ipynb
  examples/Basics/Methods-and-Parameters-for-Segmentation.ipynb
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/Example_Track_on_Radar_Segment_on_Satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  examples/Example_vorticity_tracking_model/Example_vorticity_tracking_model.ipynb
  tobac/__init__.py
Labels: release

#423 Merge 1.5.3 into main
  .github/workflows/check_formatting.yml
  CHANGELOG.md
  doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  doc/conf.py
  doc/examples.rst
  doc/examples4doc
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  doc/requirements.txt
  doc/tobac.rst
  example_requirements.txt
  examples/Basics/Idealized-Case-1_Tracking-of-a-Test-Blob-in-2D.ipynb
  examples/Basics/Idealized-Case-2_Two_crossing_Blobs.ipynb
  examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_1.ipynb
  examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_2.ipynb
  examples/Basics/Methods-and-Parameters-for-Linking.ipynb
  examples/Basics/Methods-and-Parameters-for-Segmentation.ipynb
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/Example_Track_on_Radar_Segment_on_Satellite.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  examples/Example_vorticity_tracking_model/Example_vorticity_tracking_model.ipynb
  setup.py
  tobac/__init__.py
  tobac/analysis.py
  tobac/analysis/__init__.py
  tobac/analysis/cell_analysis.py
  tobac/analysis/feature_analysis.py
  tobac/analysis/spatial.py
  tobac/feature_detection.py
  tobac/plotting.py
  tobac/segmentation.py
  tobac/tests/test_analysis_spatial.py
  tobac/tests/test_convert.py
  tobac/tests/test_decorators.py
  tobac/tests/test_sample_data.py
  tobac/tests/test_testing.py
  tobac/tests/test_tracking.py
  tobac/tests/test_utils_bulk_statistics.py
  tobac/tracking.py
  tobac/utils/bulk_statistics.py
  tobac/utils/decorators.py
  tobac/utils/general.py
  tobac/utils/internal/basic.py
  tobac/utils/internal/iris_utils.py
  tobac/utils/internal/xarray_utils.py
Labels: release
