Repository tobac-project/tobac, pull requests merged in 2024-02, with the labels that each got.

#406 Add Box Seeding Documentation to Segmentation Parameter Docs
  doc/images/box_vs_column_seeding.png
  doc/segmentation_parameters.rst
  tobac/segmentation.py
Labels: enhancement, documentation

#400 Bugfix in grid spacing
  tobac/utils/general.py
Labels: bug, enhancement

#334 Starting Backintegration of Tutorial Notebooks
  doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  doc/feature_detection/notebooks/feature_detection_filtering.ipynb
  doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
  doc/feature_detection/notebooks/n_min_threshold_example.ipynb
  doc/feature_detection/notebooks/position_threshold_example.ipynb
  example_requirements.txt
  examples/Basics/Idealized-Case-1_Tracking-of-a-Test-Blob-in-2D.ipynb
  examples/Basics/Idealized-Case-2_Two_crossing_Blobs.ipynb
  examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_1.ipynb
  examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_2.ipynb
  examples/Basics/Methods-and-Parameters-for-Linking.ipynb
  examples/Basics/Methods-and-Parameters-for-Segmentation.ipynb
  examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
  examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
  examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/Example_Track_on_Radar_Segment_on_Satellite.ipynb
  examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
  examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
  examples/Example_vorticity_tracking_model/Example_vorticity_tracking_model.ipynb
  tobac/analysis.py
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/utils/general.py
Labels: xarray transition, Tobathon
