Repository tobac-project/tobac, pull requests merged in 2024-10, with the labels that each got.

#449 Optional calculation of bulk statistics in feature detection on raw input (before smoothing)
  tobac/feature_detection.py
  tobac/segmentation.py
  tobac/tests/test_utils_bulk_statistics.py
  tobac/utils/decorators.py
Labels: enhancement

#448 Corrected error and warnings for bulk statistics when feature labels do not match labels in segmentation mask
  doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb
  tobac/tests/test_utils_bulk_statistics.py
  tobac/utils/bulk_statistics.py
Labels: bug

#452 Fix minimum distance filtering for varying vertical coordinates
  tobac/feature_detection.py
  tobac/tests/test_feature_detection.py
Labels: bug

#457 Fix JSON and Black checks
  .github/workflows/check_formatting.yml
  .github/workflows/check_json.yml
  environment-ci.yml
  tobac/feature_detection.py
  tobac/tests/test_utils_bulk_statistics.py
  tobac/utils/bulk_statistics.py
Labels: bug, Small Change
